### ISSUE TITLE
Error in useChat when parsing stream causing empty messages from AI

### ISSUE THREAD

**Issue by Ladekarl** [vercel/ai#1347] opened 2024-04-14 17:20 UTC
### Description

I was following the docs for implementing `useChat` but the responses from the stream would not show in the `messages` array returned from useChat. I would only see the user's prompts in there and not the AI reponses.

When I inspected the response from the  chat endpoint everything seemed to work fine and it was returning the correctly streamed AI response. 
By inserting a log statement in the `onError` callback in `useChat` I was able to get the following message:
```javascript
error Error: Failed to parse stream string. No separator found.
    at parseStreamPart (index.mjs:173:15)
    at Array.map (<anonymous>)
    at readDataStream (index.mjs:217:52)
    at async parseComplexResponse (index.mjs:247:36)
    at async callChatApi (index.mjs:374:12)
    at async getStreamedResponse (index.mjs:541:12)
    at async processChatStream (index.mjs:392:46)
    at async eval (index.mjs:642:13)
``` 

Finally I tried reverting to an older version and there it worked just fine. I tried bumping the versions and found out that the error started appearing in version 3.0.20.
Reverting to **3.0.19** fixed the issue.

### API route
```javascript
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const messages = body.messages ?? [];
    const previousMessages = messages.slice(0, -1);
    const currentMessageContent = messages[messages.length - 1].content;

    const model = new ChatOpenAI({
      modelName: 'gpt-3.5-turbo-1106',
      temperature: 0.2,
      apiKey: OPENAI_API_KEY,
      streaming: true
    });

    const standaloneQuestionChain = RunnableSequence.from([
      condenseQuestionPrompt,
      model,
      new StringOutputParser()
    ]);

    const pinecone = new Pinecone({ apiKey: PINECONE_API_KEY });
    const pineconeIndex = pinecone.Index(PINECONE_INDEX_NAME);

    const vectorstore = await PineconeStore.fromExistingIndex(
      new CohereEmbeddings({ model: 'multilingual-22-12' }),
      { pineconeIndex }
    );

    const retriever = vectorstore.asRetriever();

    const retrievalChain = retriever.pipe(combineDocumentsFn);

    const answerChain = RunnableSequence.from([
      {
        context: RunnableSequence.from([
          input => input.question,
          retrievalChain
        ]),
        chat_history: input => input.chat_history,
        question: input => input.question
      },
      answerPrompt,
      model
    ]);

    const conversationalRetrievalQAChain = RunnableSequence.from([
      {
        question: standaloneQuestionChain,
        chat_history: input => input.chat_history
      },
      answerChain,
      new BytesOutputParser()
    ]);

    const stream = await conversationalRetrievalQAChain.stream({
      question: currentMessageContent,
      chat_history: formatVercelMessages(previousMessages)
    });

    return new StreamingTextResponse(stream);
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: e.status ?? 500 });
  }
}
``` 
### Client component
```javascript
'use client';

import { useChat } from 'ai/react';
import type { FormEvent } from 'react';

import { Box, Button, Container, TextField, Typography } from '@mui/material';

export default function Chat() {
  const {
    messages,
    input,
    handleInputChange,
    handleSubmit,
    isLoading: chatEndpointIsLoading
  } = useChat();

  async function sendMessage(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!messages.length) {
      await new Promise(resolve => setTimeout(resolve, 300));
    }
    if (chatEndpointIsLoading) {
      return;
    }
    handleSubmit(e);
  }

  return (
    <Container>
      {messages.length === 0 ? 'No messages' : ''}

      {messages.length > 0
        ? [...messages].reverse().map(m => {
            return (
              <Box key={m.id}>
                <Typography>{m.content}</Typography>
              </Box>
            );
          })
        : ''}
      <Container>
        <form onSubmit={sendMessage}>
          <TextField value={input} onChange={handleInputChange} />
          <Button type="submit">Send</Button>
        </form>
      </Container>
    </Container>
  );
}

```

**Comment by lgrammel** [comment] 2024-04-15 07:08
Duplicate of https://github.com/vercel/ai/issues/1316

See https://github.com/vercel/ai/issues/1316#issuecomment-2048346351 for upgrade instructions.

**Comment by mauriceackel** [comment] 2024-04-15 10:04
I don't understand why this is resolved as a duplicate. The other issue seems to be related to parsing the StreamingTextResponse manually, while this is about using `useChat`.

I just installed version (3.0.22), removed my package-lock file, node_modules folder and .next build folder. Even after that, I got the same error as above (i.e. `error Error: Failed to parse stream string. No separator found.`)

**Comment by johnson-liang** [comment] 2024-04-15 11:47
Also got `Failed to parse stream string.` on the error callback.

It turns out that the versions of `ai` package in our API (`ai@3.0.13` on Express.JS server using `streamToResponse`) and UI (`ai@3.0.21` in React.js application with `useChat`) dos not match.

It seems that there is [a breaking change](https://github.com/vercel/ai/issues/1316) on 3.0.20, so that both API and UI must both use `ai` >= v3.0.20, or both use `ai` < v3.0.20.

We really do not expect such incompatibility in patch versions though, and it took us hours to debug and reach here.

**Comment by lgrammel** [comment] 2024-04-15 14:23
@mauriceackel in your first example, langchain returns a text stream that gets forwarded. I'm working on making useChat/useCompletion compatible with it again, see https://github.com/vercel/ai/pull/1350 

In your current example, this might be sufficient:

```
return new StreamingTextResponse(
  stream.pipeThrough(createStreamDataTransformer()),
);
```

**Comment by Ladekarl** [comment] 2024-04-15 17:55
> @mauriceackel in your first example, langchain returns a text stream that gets forwarded. I'm working on making useChat/useCompletion compatible with it again, see #1350
> 
> In your current example, this might be sufficient:
> 
> ```
> return new StreamingTextResponse(
>   stream.pipeThrough(createStreamDataTransformer()),
> );
> ```
> 
> i.e. you might not need data, the important part is the stream transformation

This worked for me. 
Thanks 👍

**Comment by pedrocarnevale** [comment] 2024-04-15 20:36
> @mauriceackel in your first example, langchain returns a text stream that gets forwarded. I'm working on making

I'm getting this error in this solution:

```
Expected 1 arguments, but got 0.ts(2554)
index.d.ts(927, 46): An argument for 'experimental_streamData' was not provided.
```

**Comment by pedrocarnevale** [comment] 2024-04-15 21:14
> Okay, so it seems like the default mode for streaming responses is to include stream data now. I was able to get streaming work with `3.0.22` using the following setup:
> 
> ```ts
> const data = new StreamData();
> 
> const stream = await pipeline.stream(
>   question,
>   {
>     callbacks: [{
>       handleChainEnd: (_, __, parentRunId) => {
>         if (parentRunId === undefined) data.close();
>       },
>     }],
>   },
> );
> 
> return new StreamingTextResponse(
>   stream.pipeThrough(createStreamDataTransformer()),
>   undefined,
>   data,
> );
> ```
> 
> @lgrammel, so we still need to manually close the StreamData object?

With this solution, this happens to me

![image](https://github.com/vercel/ai/assets/42678222/d9450d05-2486-4143-8a16-727a48590f1a)

**Comment by connorblack** [comment] 2024-04-15 23:18
> stream.pipeThrough(createStreamDataTransformer()),

this works for me, no need to stub `StreamData`

**Comment by lgrammel** [comment] 2024-04-16 07:14
> > Okay, so it seems like the default mode for streaming responses is to include stream data now. I was able to get streaming work with `3.0.22` using the following setup:
> > ```ts
> > const data = new StreamData();
> > 
> > const stream = await pipeline.stream(
> >   question,
> >   {
> >     callbacks: [{
> >       handleChainEnd: (_, __, parentRunId) => {
> >         if (parentRunId === undefined) data.close();
> >       },
> >     }],
> >   },
> > );
> > 
> > return new StreamingTextResponse(
> >   stream.pipeThrough(createStreamDataTransformer()),
> >   undefined,
> >   data,
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @lgrammel, so we still need to manually close the StreamData object?
> 
> With this solution, this happens to me
> 
> ![image](https://private-user-images.githubusercontent.com/42678222/322631225-d9450d05-2486-4143-8a16-727a48590f1a.png

This can happen when you use an older version of the AI SDK on the client. Please make sure you use `>= 3.0.20` on the client (ideally the client version should match the server version)

**Comment by lgrammel** [comment] 2024-04-16 07:15
@pedrocarnevale This can happen when you use an older version of the AI SDK on the client. Please make sure you use >= 3.0.20 on the client (ideally the client version should match the server version)

**Comment by pedrocarnevale** [comment] 2024-04-16 12:07
@lgrammel I have this in my package.json file `"ai": "^3.0.22"`. This "ai" package version reffers to AI SDK on the server, right?  How do I know the version of the AI SDK on the client in my nextjs project?

**Comment by lgrammel** [comment] 2024-04-16 14:21
> @lgrammel I have this in my package.json file `"ai": "^3.0.22"`. This "ai" package version reffers to AI SDK on the server, right? How do I know the version of the AI SDK on the client in my nextjs project?

It depends on your project. If you use e.g. Next.js there would most likely be only 1 package.json file for both server & client code.

**Closed** 2024-05-11 21:22 UTC

**Comment by jasonunderstood** [comment] 2024-06-20 21:30
> @mauriceackel in your first example, langchain returns a text stream that gets forwarded. I'm working on making useChat/useCompletion compatible with it again, see #1350
> 
> In your current example, this might be sufficient:
> 
> ```
> return new StreamingTextResponse(
>   stream.pipeThrough(createStreamDataTransformer()),
> );
> ```
> 
> i.e. you might not need data, the important part is the stream transformation

Would it be possible to add this to the docs?

**Comment by lgrammel** [comment] 2026-07-22 17:53
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete patch-version regression in existing streaming behavior, confirmed by a maintainer and addressed with a compatibility fix.

### Evidence
- `useChat` fails to parse a plain text stream with “Failed to parse stream string. No separator found,” leaving assistant messages empty.
- The behavior regressed in `ai@3.0.20`; reverting to 3.0.19 restored functionality.
- A maintainer confirmed that LangChain text streams had become incompatible with `useChat`/`useCompletion` and linked PR #1350 to restore compatibility.
