### ISSUE TITLE
The done in unstable_onSetAIState doesnt work, it always gives False. Making it hard to save it to a database

### ISSUE THREAD

**Issue by kaarthik108** [vercel/ai#1340] opened 2024-04-13 06:57 UTC
### Description

unstable_onSetAIState streams the state messages,  but unfornutaley not able to keep track of when it finishes streaming. 

The done prop doesnt work, always returns false.

### Code example

```
  unstable_onSetAIState: async ({ state, done, key }) => {
    "use server";

    const { chatId, messages } = state;
    console.log("messages------\n\n", messages);

    const title = messages[0].content.substring(0, 100);
    const path = `/chat/${chatId}`;
    const chat: Chat = {
      id: chatId,
      title,
      messages: messages,
      path,
      userId: "test",
    };
    await saveChat(chat);
  },
});

```

This streams messages making it imposiible to save to a database 

`<p style="margin: 8px 0px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(33, 37, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><small><strong>rgument #0:</strong></small></p><div data-code="id#6232" style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(33, 37, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-family: &quot;Cascadia Code&quot;, Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 11px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; font-variation-settings: normal; line-height: 17px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(171, 178, 191);">  </span><span class="mtk11" style="color: rgb(152, 195, 121);">'messages------</span><span class="mtk8" style="color: rgb(86, 182, 194);">\n\n</span><span class="mtk11" style="color: rgb(152, 195, 121);">'</span></div></span></div><p style="margin: 8px 0px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(33, 37, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><small><strong> messages:</strong></small></p><div data-code="id#6233" style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(33, 37, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-family: &quot;Cascadia Code&quot;, Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 11px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; font-variation-settings: normal; line-height: 17px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(171, 178, 191);">  </span><span class="mtk6" style="color: rgb(97, 175, 239);">Array</span><span class="mtk1" style="color: rgb(171, 178, 191);">(</span><span class="mtk7" style="color: rgb(209, 154, 102);">10</span><span class="mtk1" style="color: rgb(171, 178, 191);">) [</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'gdSHceT'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'user'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'</span><span class="mtk8" style="color: rgb(86, 182, 194);">\n\n</span><span class="mtk11" style="color: rgb(152, 195, 121);">hi'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello!'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How can'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How can I'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    { </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">, </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How can I assist'</span><span class="mtk1" style="color: rgb(171, 178, 191);"> },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    {</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">,</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">,</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How can I assist you'</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    {</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">,</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">,</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How can I assist you today'</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    },</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    {</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">id</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'test'</span><span class="mtk1" style="color: rgb(171, 178, 191);">,</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">role</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'assistant'</span><span class="mtk1" style="color: rgb(171, 178, 191);">,</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">      </span><span class="mtk9" style="color: rgb(224, 108, 117);">content</span><span class="mtk8" style="color: rgb(86, 182, 194);">:</span><span class="mtk1" style="color: rgb(171, 178, 191);"> </span><span class="mtk11" style="color: rgb(152, 195, 121);">'Hello! How can I assist you today?'</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">    }</span><br><span class="mtk1" style="color: rgb(171, 178, 191);">  ]</span></div></span></div>
18:52:12.390 \| +47 ms \| next.js server |  
-- | --

<p style="margin: 8px 0px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(33, 37, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><small><strong> argument #0:</strong></small></p><div data-code="id#6242" style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(33, 37, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-family: &quot;Cascadia Code&quot;, Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 11px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; font-variation-settings: normal; line-height: 17px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(171, 178, 191);">  </span><span class="mtk11" style="color: rgb(152, 195, 121);">'messages------</span><span class="mtk8" style="color: rgb(86, 182, 194);">\n\n</span><span class="mtk11" style="color: rgb(152, 195, 121);">'</span></div></span></div>`

**Comment by jeremyphilemon** [comment] 2024-04-13 09:52
@kaarthik108 `done` returns true only when `.done()` is called on the mutable ai state. Can you confirm you're seeing the same behavior after marking your state as done?

**Comment by kaarthik108** [comment] 2024-04-13 20:36
Hey @jeremyphilemon , I do have `aiState.done` on all of my function call and text-delta methods. but the done is still giving 'False'

**Comment by kaarthik108** [comment] 2024-04-13 20:38
I got a workaround to save it from inside the submit function, but would be good to do it on unstable_onsetaistate instead. 


```


async function submitUserMessage(content: string) {
  "use server";
  const aiState = getMutableAIState();

  aiState.update({
    ...aiState.get(),
    messages: [
      ...aiState.get().messages,
      {
        id: nanoid(),
        role: "user",
        content: `${aiState.get().interactions.join("\n\n")}\n\n${content}`,
      },
    ],
  });

  const history = aiState.get().messages.map((message: any) => ({
    role: message.role,
    content: message.content,
  }));

  const textStream = createStreamableValue("");
  const spinnerStream = createStreamableUI(<BotCard>{spinner}</BotCard>);
  // const skeletonStream = createStreamableUI(<AreaSkeleton />);
  const messageStream = createStreamableUI(null);
  const uiStream = createStreamableUI();

  const getDDL = await getContext(content);

  (async () => {
    try {
      const result = await experimental_streamText({
        model: openai.chat("gpt-4-turbo"),
        temperature: 0,
        tools: {
          query_data: {
            description:
              "Query the data from the sqlite database and return the results.",
            parameters: querySchema,
          },
        },
        system: `
You are a Sqlite data analytics assistant. 
      `,
        messages: [...history],
      });

      let textContent = "";
      spinnerStream.done(null);

      for await (const delta of result.fullStream) {
        const { type } = delta;

        if (type === "text-delta") {
          const { textDelta } = delta;

          textContent += textDelta;

          messageStream.update(<BotMessage content={textContent} />);

          // aiState.update({
          //   ...aiState.get(),
          //   messages: [
          //     ...aiState.get().messages,
          //     {
          //       id: "1",
          //       role: "assistant",
          //       content: textContent,
          //     },
          //   ],
          // });

          aiState.done({
            ...aiState.get(),
            interactions: [],
            messages: [
              ...aiState.get().messages,
              {
                id: Date.now(),
                role: "assistant",
                content: textContent,
              },
            ],
          });
        } else if (type === "tool-call") {
          const { toolName, args } = delta;

          if (toolName === "query_data") {
            const {
              format,
              title,
              timeField,
              categories,
              index,
              yaxis,
              size,
              query,
            } = args;

            uiStream.update(
              <BotCard>
                <ChartWrapper props={args} />
              </BotCard>
            );

            aiState.done({
              ...aiState.get(),
              interactions: [],
              messages: [
                ...aiState.get().messages,
                {
                  id: nanoid(),
                  role: "assistant",
                  content: `[Sqlite query results for code: ${query} and chart format: ${format} with categories: ${categories} and data index: ${index} and yaxis: ${yaxis} and size: ${size}]`,
                  display: {
                    name: "query_data",
                    props: args,
                  },
                },
              ],
            });
          }
        }
      }
      const ms = aiState.get().messages;
      const id = aiState.get().chatId;
      // @ts-ignore
      const latestMessages: _Message[] = Array.from(
        new Map(
          ms.filter(isMessage).map((msg: Message) => [msg.role, msg])
        ).values()
      );
      await saveChat({
        id,
        title: latestMessages.map((msg) => msg.content).join("\n\n"),
        messages: latestMessages,
        path: `/chat/${id}`,
        userId: "test",
      });

      uiStream.done();
      textStream.done();
      messageStream.done();
    } catch (e) {
      console.error(e);

      const error = new Error("The AI got into some problem.");
      uiStream.error(error);
      textStream.error(error);
      messageStream.error(error);
      // @ts-ignore
      aiState.done();
    }
  })();

  return {
    id: nanoid(),
    attachments: uiStream.value,
    spinner: spinnerStream.value,
    display: messageStream.value,
  };
}

```

**Comment by Phoenix-Alpha** [comment] 2024-05-06 16:56
For me done works but saveChat seems to be not working in some cases. I guess it's when the message content is large and I move to different chat page before saving finishes

**Comment by MaxLeiter** [comment] 2024-07-08 20:54
Hey @Phoenix-Alpha if this is still an issue, please open a new issue with more details. Closing as we haven't had new reports of `onSetAIState` not working.

**Closed by MaxLeiter** 2024-07-08 20:54 UTC

**Comment by Godrules500** [comment] 2024-07-17 03:36
@MaxLeiter  I am still having this issue.

If I set the state with useAIState, it is not updating properly. It's causing an issue when switching between chats where the last message and prompt is left off because useAIState doesn't seem to be working properly. [87](https://github.com/vercel/ai-chatbot/issues/87)

**Comment by Godrules500** [comment] 2024-07-17 03:39
@MaxLeiter  I am still having this issue.

If I set the state with useAIState, it is not updating properly. It's causing an issue when switching between chats where the last message and prompt is left off because useAIState doesn't seem to be working properly. [364](https://github.com/vercel/ai-chatbot/issues/364)

**Comment by lgrammel** [comment] 2026-07-22 17:54
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes a concrete failure of the existing AI state completion callback: `done` does not reflect calls to `aiState.done()` as expected.

### Evidence
- Reporter states `unstable_onSetAIState` always receives `done: false`, preventing persistence after streaming completes.
- Reporter confirms calling `aiState.done(...)` in text-delta and tool-call paths but still does not observe `done: true`.
- A later commenter reports a related AI state update problem when switching chats; the maintainer closed the issue due to limited reports rather than identifying intended behavior or misuse.
