### ISSUE TITLE
Got '0:" !"\n' out of very strange characters from the stream since the last update, and the document is not updated.

### ISSUE THREAD

**Issue by Melvynx** [vercel/ai#1370] opened 2024-04-17 06:36 UTC
### Description

Since the last update, the AI SDK now fully supports custom file reading.

![CleanShot 2024-04-17 at 14 34 24@2x](https://github.com/vercel/ai/assets/56388157/65e14a76-f583-4370-ba18-7cb5dd5a5212)

### Code example

I use ReadStream to read stream from OpenAI : 

```ts
export const readStream = async (
  stream: ReadableStream,
  onChunkValue: (chunk: string) => void
) => {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let done = false;

  let result = '';

  while (!done) {
    // eslint-disable-next-line no-await-in-loop
    const { value, done: doneReading } = await reader.read();
    done = doneReading;
    const chunkValue = decoder.decode(value);

    result += chunkValue;

    onChunkValue(result);
  }
};

```

And follow the documentation for the app router : 

```ts
import OpenAI from 'openai';
import { OpenAIStream, StreamingTextResponse } from 'ai';
 
// Optional, but recommended: run on the edge runtime.
// See https://vercel.com/docs/concepts/functions/edge-functions
export const runtime = 'edge';
 
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});
 
export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json();
 
  // Request the OpenAI API for the response based on the prompt
  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: messages,
  });
 
  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response);
 
  // Respond with the stream
  return new StreamingTextResponse(stream);
}
```

### Additional context

In this file from the Next.js example, I see that the documentation seems to not be updated: https://github.com/vercel/ai/blob/main/examples/next-openai/app/api/chat/route.ts

**Comment by lgrammel** [comment] 2024-04-17 06:41
Duplicate of https://github.com/vercel/ai/issues/1316

See https://github.com/vercel/ai/issues/1316#issuecomment-2048346351 for solutions

**Closed by lgrammel** 2024-04-17 06:41 UTC

**Comment by lgrammel** [comment] 2026-07-22 17:53
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a regression in existing streaming behavior that causes encoded stream protocol data to be displayed as text. Although it is a duplicate and may involve outdated usage or documentation, the primary report is a concrete runtime failure.

### Evidence
- After the last SDK update, streamed output is rendered with protocol prefixes such as `0:"..."` instead of plain text.
- The reporter follows the documented `OpenAIStream` and `StreamingTextResponse` setup but their existing custom stream reader no longer produces usable output.
- A maintainer identifies it as a duplicate of #1316 and links to solutions, confirming it is a known concrete streaming issue.
