### ISSUE TITLE
Streaming or yield not working on Vercel

### ISSUE THREAD

**Issue by stephenkalnoske-sans** [vercel/ai#1187] opened 2024-03-19 20:17 UTC
### Description

I set up an app just like in the examples. When I run it locally, it streams and yields from function* generators in the render functions perfectly. When I upload to Vercel and run it through there, there is no streaming. Responses still come in, but I don't see any of my spinners or loading messages when sent with yield.

I've made sure to update the ai, openai, and next packages to latest.

**Comment by stephenkalnoske-sans** [comment] 2024-03-19 23:01
I solved this by adding 

`export const runtime = "edge"`

in my page.tsx

**Comment by lgrammel** [comment] 2024-03-20 07:32
@stephenkalnoske-sans which docs page were you looking at?

**Comment by stephenkalnoske-sans** [comment] 2024-03-20 12:47
https://sdk.vercel.ai/docs/concepts/ai-rsc

https://sdk.vercel.ai/docs/api-reference/generative-ui/render

**Comment by miurla** [comment] 2024-04-18 14:57
@lgrammel 

I have the same issue.
I created a minimum project with the example code in the [docs](https://sdk.vercel.ai/docs/concepts/ai-rsc) and verified it.
https://github.com/miurla/my-ai-app/blob/68fcd6540db4a4652093c0ae621a87367471fdcb/app/page.tsx#L7-L8

Is it correct to set `export const runtime = "edge"`?
In Vercel's ChatBot, it doesn't seem to be set to edge, but it works.
Are there any necessary settings in Vercel?

**Comment by lgrammel** [comment] 2024-04-18 15:09
@miurla can you try `export const dynamic = 'force-dynamic'`? (edge might not be needed)

CC @shuding re RSC

**Comment by miurla** [comment] 2024-04-18 15:27
@lgrammel Thank you for your quick response! I tried it, but it's not working.

https://github.com/miurla/my-ai-app/blob/main/app/page.tsx#L8

**Comment by miurla** [comment] 2024-04-23 03:20
## Additional information
By removing `use client` from page.tsx and setting `export const dynamic = 'force-dynamic'`, streaming started working.
However, a client-side exception occurs.

https://github.com/miurla/morphic/blob/test-stream/app/page.tsx#L3

**Comment by miurla** [comment] 2024-05-09 01:34
> There was a bug up until 14.2.2 with streaming + server actions + Node.js that has since been resolved.
https://github.com/miurla/morphic/pull/5#issuecomment-2100788459

This issue seems to have been caused by a combination of factors. It has been resolved in 14.2.3. I think we can close this issue.

**Comment by D4RK5IDE** [comment] 2024-08-21 07:48
I have a similar problem. But yield doesn't work even on local. I have installed the latest packages ai, openai, and next.

**Comment by D4RK5IDE** [comment] 2024-08-21 09:10
I'm sorry, it was my mistake, everything works. You can close this issue.

**Closed** 2024-08-21 09:29 UTC
Labels: bug, ai/rsc

**Comment by lgrammel** [comment] 2026-07-22 17:59
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete failure of existing streaming behavior. Although an initial workaround prompted a documentation suggestion, later investigation attributed the failure to a resolved Next.js bug rather than missing documentation.

### Evidence
- Streaming and generator yields worked locally but failed after deployment to Vercel.
- A reproducer confirmed streaming issues with server actions on the Node.js runtime.
- A comment identified a streaming bug in Next.js through 14.2.2 and confirmed it was resolved in 14.2.3.
