### ISSUE TITLE
Remix – ReadableStream type mismatch: The "transform.readable" property must be an instance of ReadableStream. Received an instance of ReadableStream

### ISSUE THREAD

**Issue by Klingefjord** [vercel/ai#602] opened 2023-09-27 05:58 UTC
I am using Remix (2.0.1) and Vercel AI (2.2.13).

I am getting this error when submitting a chat message in production (deployed on Vercel using the Remix template). 

The error does not occur locally:

```
{ url: '/chat/completions' }
TypeError [ERR_INVALID_ARG_TYPE]: The "transform.readable" property must be an instance of ReadableStream. Received an instance of ReadableStream
    at new NodeError (node:internal/errors:405:5)
    at ReadableStream.pipeThrough (node:internal/webstreams/readablestream:363:13)
    at AIStream (/var/task/node_modules/ai/dist/index.js:139:29)
    at OpenAIStream (/var/task/node_modules/ai/dist/index.js:360:14)
    at action4 (/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js:12965:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.callRouteActionRR (/var/task/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
    at async callLoaderOrAction (/var/task/node_modules/@remix-run/router/dist/router.cjs.js:3903:16)
    at async submit (/var/task/node_modules/@remix-run/router/dist/router.cjs.js:3275:16)
    at async queryImpl (/var/task/node_modules/@remix-run/router/dist/router.cjs.js:3233:22) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Code to replicate:

/api/chat

```
import { ChatCompletionRequestMessage, OpenAIApi, Configuration } from "openai-edge"
import {
  OpenAIStream,
  StreamingTextResponse,
} from "ai"

export const action: ActionFunction = async ({
  request,
}: ActionFunctionArgs): Promise<Response> => {
  const json = await request.json()
  const { messages } = json
  const openai = new OpenAIApi(
     new Configuration({
       apiKey: xxxx
     })
  )
  const response = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: messages,
      temperature: 0.7,
      stream: true,
    })
  const stream = OpenAIStream(response)
  return new StreamingTextResponse(stream)
}
```

**Comment by Klingefjord** [comment] 2023-09-27 06:06
Also added here: https://github.com/remix-run/remix/issues/7547

**Comment by Klingefjord** [comment] 2023-10-03 22:45
Actually, probably not a problem with AI package, nor Remix, but the remix build tooling from Vercel.

https://github.com/vercel/remix/issues/60

**Comment by MaxLeiter** [comment] 2023-10-04 22:07
Are you using node 18+?

**Comment by Klingefjord** [comment] 2023-10-06 09:21
> Are you using node 18+?

Yes, 18.7

**Comment by jacobhjkim** [comment] 2023-11-12 09:43
Is this resolved? https://github.com/vercel/remix/issues/60 and https://github.com/vercel/remix/pull/56 seems to have resolved it.

**Comment by Klingefjord** [comment] 2023-11-13 17:19
> vercel/remix#60

Nope, still an issue! Tried upgrading to latest remix and vercel ai, still the same error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "transform.readable" property must be an instance of ReadableStream. Received an instance of ReadableStream
```

**Comment by MaxLeiter** [comment] 2023-11-13 20:42
Hey @Klingefjord, could you please create a reproduction so we can check this out?

**Comment by maxfi** [comment] 2024-04-07 05:44
Probably related: https://github.com/vercel/remix/issues/62

**Comment by peterje** [comment] 2024-04-23 10:20
Omitting the call to `installGlobals` resolved this locally for me. That function is supposed to be the solution to these problems by polyfilling the fetch standard, but seems to have the opposite effect here.

**Comment by nsijwali** [comment] 2024-05-14 18:06
is this issue resolved?? facing same

**Comment by MaxLeiter** [comment] 2024-06-11 00:42
@nsijwali did you try removing `installGlobals`? I'm closing this as it seems like a Remix-related bug more than an AI SDK one.

**Closed by MaxLeiter** 2024-06-11 00:42 UTC

**Comment by lgrammel** [comment] 2026-07-22 18:25
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the issue reports a concrete runtime error involving `OpenAIStream`, subsequent investigation attributes it to Remix tooling/polyfills rather than behavior in the AI SDK. It is therefore not an actionable AI SDK bug or feature request.

### Evidence
- The failure occurs only in the deployed Remix/Vercel environment, not locally.
- The reporter later stated it was probably caused by Vercel's Remix build tooling rather than the AI SDK.
- A workaround was reported by omitting Remix's `installGlobals` call.
- The maintainer closed the issue as a Remix-related bug rather than an AI SDK bug.
