### ISSUE TITLE
[zod dependency] Is it okay to add zod dependency to the main package?

### ISSUE THREAD

**Issue by jikkuatwork** [vercel/ai#1680] opened 2024-05-24 04:49 UTC
### Description

I was testing the ai core examples using `bun run` *without installing* or setting up package.json. `bun` typically resolves all necessary dependencies in the background but it failed on the very first example complaining `zod` was missing. I added the following explicitly to make it work. I believe this is happening because the package assumes zod will be in dependency tree, which it is not. I was thinking to do a PR but when I saw the package had zero dependencies (and didn't want to add one) I thought I will ask it here for any other alternatives or something I am missing.

Note: I know setting up a package.json with zod should solve it. But, I love this aspect of bun to run a file without needing to dirty the directory with a node_modules folder.

``` ts
import { openai } from "@ai-sdk/openai"
import { generateText } from "ai"
import { z } from "zod" // ADDED

async function main() {
  const result = await generateText({
    model: openai("gpt-4o"),
    prompt: "Tell me a joke.",
  })

  console.log(result.text)
  z // ADDED
}

main().catch(console.error)
```

### Code example

import { openai } from "@ai-sdk/openai"
import { generateText } from "ai"
import { z } from "zod" // ADDED

async function main() {
  const result = await generateText({
    model: openai("gpt-4o"),
    prompt: "Tell me a joke.",
  })

  console.log(result.text)
  z // ADDED
}

main().catch(console.error)

**Comment by lgrammel** [comment] 2024-05-24 06:40
The issue is that while the `ai` package does not require Zod unless you pass it in (Zod is optional), the provider packages do and it's currently marked as optional in them. I'll provide a fix.

**Comment by jikkuatwork** [comment] 2024-05-24 08:01
Great, thanks! Really love the ergonomics of being able to run a script with `bun run`; this will enable me have simple CLI scripts with AI SDK! Thanks again @lgrammel!

**Comment by lgrammel** [comment] 2024-05-27 12:13
https://github.com/vercel/ai/pull/1700

**Closed** 2024-05-27 12:25 UTC
Labels: bug, ai/provider

**Comment by lgrammel** [comment] 2026-07-22 17:39
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete dependency declaration defect: provider packages require Zod at runtime, but their package metadata marked it optional, causing otherwise valid usage to fail.

### Evidence
- Running the AI Core example with Bun fails because the OpenAI provider package cannot resolve `zod`.
- The maintainer confirmed that provider packages require Zod but incorrectly marked it as optional and stated that a fix would be provided.
- The maintainer linked PR #1700 as the resolution.
