### ISSUE TITLE
Add possibility to clear experimental_StreamData

### ISSUE THREAD

**Issue by Yoha485** [vercel/ai#648] opened 2023-10-20 08:33 UTC
### Feature Description

It's only possible to call `append` on experimental_StreamData object. It would be creat if you could add a functionality that allows you to clear everything that you appended before

**Comment by MaxLeiter** [comment] 2023-10-20 21:58
Thanks for the issue, going to close as a dupe of #586. A PR exploring the API would be appreciated!

**Closed by MaxLeiter** 2023-10-20 21:58 UTC

**Comment by lgrammel** [comment] 2026-07-22 18:22
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for an API capability that does not currently exist, rather than a report that existing behavior is broken.

### Evidence
- The issue requests a new method to clear previously appended values from `experimental_StreamData`, which currently only supports `append`.
- The maintainer identifies it as a duplicate of #586 and invites a PR exploring the API.
