### ISSUE TITLE
hugging-face provider document not accessed

### ISSUE THREAD

**Issue by fport** [vercel/ai#1112] opened 2024-03-06 08:29 UTC
### Description

hugging-face provider document not accessed => https://sdk.vercel.ai/docs/guides/providers/hugging-face

**Comment by CollComm** [comment] 2024-03-06 12:27
Issue observed is identical to the one described; merged with https://github.com/vercel/ai/issues/1115

**Comment by lgrammel** [comment] 2024-03-11 13:38
There is a type in the URL, the correct URL is https://sdk.vercel.ai/docs/guides/providers/huggingface

**Closed by lgrammel** 2024-03-11 13:38 UTC

**Comment by lgrammel** [comment] 2026-07-22 18:02
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support/duplicate report caused by an incorrect URL, with no documented request to change the SDK or its documentation.

### Evidence
- The reported URL uses an incorrect `hugging-face` path.
- A maintainer supplied the working `huggingface` URL, indicating the problem was a typo rather than inaccessible documentation.
- A comment notes the report was merged with issue #1115.
