### ISSUE TITLE
TypeScript errors with Node

### ISSUE THREAD

**Issue by mishushakov** [vercel/ai#1403] opened 2024-04-22 14:24 UTC
### Description

Using Node.js (v20.12.2) and typescript 5.4.5

```
tsc -p tsconfig.json
```

```
node_modules/ai/dist/index.d.ts:5:45 - error TS2307: Cannot find module '@mistralai/mistralai' or its corresponding type declarations.

5 import { ChatCompletionResponseChunk } from '@mistralai/mistralai';
                                              ~~~~~~~~~~~~~~~~~~~~~~

node_modules/ai/dist/index.d.ts:770:19 - error TS2503: Cannot find namespace 'JSX'.

770     ui?: string | JSX.Element | JSX.Element[] | null | undefined;
                      ~~~

node_modules/ai/dist/index.d.ts:770:33 - error TS2503: Cannot find namespace 'JSX'.

770     ui?: string | JSX.Element | JSX.Element[] | null | undefined;
                                    ~~~

node_modules/ai/dist/index.d.ts:1734:24 - error TS2503: Cannot find namespace 'JSX'.

1734 type UINode = string | JSX.Element | JSX.Element[] | null | undefined;
                            ~~~

node_modules/ai/dist/index.d.ts:1734:38 - error TS2503: Cannot find namespace 'JSX'.

1734 type UINode = string | JSX.Element | JSX.Element[] | null | undefined;
                                          ~~~


Found 5 errors in the same file, starting at: node_modules/ai/dist/index.d.ts:5
```

### Code example

```
import { OpenAI } from '@ai-sdk/openai';
import { LanguageModelV1 } from '@ai-sdk/provider'
import { experimental_generateObject, UserContent } from 'ai'
```

### Additional context

My tsconfig:

```
{
  "compilerOptions": {
    "outDir": "dist",
    "declaration": true,
    "lib": ["ESNext", "DOM"],
    "module": "NodeNext",
    "target": "ESNext",
    "moduleResolution": "NodeNext"
  },
  "include": ["src/**/*.ts"]
}
```

**Comment by lgrammel** [comment] 2024-04-22 15:06
Fix: https://github.com/vercel/ai/pull/1406

**Comment by mishushakov** [comment] 2024-04-22 16:53
Awesome! Could you also help me out with the JSX type errors? I'm not using React
Danke.

**Comment by lgrammel** [comment] 2024-04-23 06:45
The JSX issue is risky to fix. Can you try installing just the React types and see if that helps?

```
  "@types/react": "^18.2.8",
```

**Comment by mishushakov** [comment] 2024-04-23 13:14
Fixes it for me (only getting the Mistral error now)! Can I ask you to keep this issue in mind, because it's very non-obvious for Node users.

**Comment by xdotli** [comment] 2024-09-06 21:58
> The JSX issue is risky to fix. Can you try installing just the React types and see if that helps?
> 
> ```
>   "@types/react": "^18.2.8",
> ```

Encountering same issue on express backend without react types. Resolved by installing types as a devDependency. Maybe add this to the document for express users?

**Comment by lgrammel** [comment] 2024-09-09 14:41
https://sdk.vercel.ai/docs/troubleshooting/common-issues/typescript-cannot-find-namespace-jsx

**Comment by lgrammel** [comment] 2024-11-26 15:01
should be resolved in AI SDK 4

**Closed by lgrammel** 2024-11-26 15:01 UTC
Labels: bug, ai/ui

**Comment by lgrammel** [comment] 2026-07-22 17:51
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete TypeScript declaration failures in existing SDK behavior, confirmed by maintainer fixes and resolution in a later release.

### Evidence
- TypeScript compilation fails in a Node.js project because the SDK declarations reference a missing Mistral module and the unavailable JSX namespace.
- A maintainer linked PR #1406 as a fix and later stated the issue should be resolved in AI SDK 4.
- Installing @types/react only worked around the JSX errors; the Mistral declaration error remained.
