### ISSUE TITLE
addToolResult / convertToCoreMessages does not seem to be working

### ISSUE THREAD

**Issue by krthush** [vercel/ai#3349] opened 2024-10-23 19:07 UTC
There seems to be an issue with the addToolResult and the way it interacts with convertToCoreMessages
When the user reacts to the tools request (e.g. by pressing Yes/No), addToolResult calls the chat API but we get an `An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'.` error. When looking into the logs I noticed that this might be more an issue of convertToCoreMessages, since the raw messages do have the result, but the conversion doesn't.

<img width="1262" alt="image" src="https://github.com/user-attachments/assets/76158f7f-be30-4d66-84cd-e1156259e040">

### To recreate:
Start a fresh next project following the instructions here: https://sdk.vercel.ai/docs/getting-started/nextjs-app-router
Add the example code from: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling#example
Then ask to run the tool and click Yes/No

**Comment by lgrammel** [comment] 2024-10-24 06:57
@krthush did this issue start with a recent update?

There were some changes recently to the conversion: https://github.com/vercel/ai/pull/3320

Could you check out if it works w/ `ai@3.4.17`?

**Comment by krthush** [comment] 2024-10-25 00:49
@lgrammel Thanks!!! Just tested it with the older version of `ai@3.4.17` and you are correct it works in that version

I'll stick to the older version for now then, can you let me know / close this issue when its updated and working fine for the newer versions?

Thanks again :)

**Comment by sreyemnayr** [comment] 2024-10-25 15:36
Getting hit with this today as well - if it's helpful in debugging, the onToolCall callback for useChat does still work as you'd expect it to.

**Comment by lgrammel** [comment] 2024-10-25 17:44
reverted, should be fixed in the latest version

**Closed** 2024-10-25 17:43 UTC

**Comment by lgrammel** [comment] 2026-07-22 16:45
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a confirmed regression in existing tool-result message conversion that caused valid tool interactions to fail.

### Evidence
- `addToolResult` triggered an API error because `convertToCoreMessages` omitted the tool result even though it was present in the raw message.
- The issue was reproducible using the documented Next.js tool-calling example by clicking Yes/No.
- The reporter confirmed the behavior worked in `ai@3.4.17`, identifying a regression in newer versions.
- A maintainer reverted the recent conversion change and stated it was fixed in the latest version.
