### ISSUE TITLE
`onFinish` is never called in `useChat` args

### ISSUE THREAD

**Issue by rob-gordon** [vercel/ai#1248] opened 2024-03-28 15:07 UTC
### Description

Currently running a bit of code in the `onFinish` handler of `useChat`. It's never called. The streaming works just fine but the handler isn't called.

Here you can see the specific line where we would get a console log if it were running:
https://github.com/Frostwork-Media/back-of-the-envelope/blob/19a3e1fdf3d24b36206b01fcc1c1c9088c88b4db/src/app/_components/Chat.tsx#L30-L31

You can test it for yourself at https://backoftheenvelope.app/ or pull the code and try locally.

### Code example

```tsx
const {
    messages,
    input,
    handleInputChange,
    handleSubmit,
    isLoading,
    setMessages,
    reload,
  } = useChat({
    onFinish() {
      console.log("onFinish() ran.");
    },
});
```

### Additional context

Running Next 14, App Router, Served on vercel, running with `bun`
Repository: https://github.com/Frostwork-Media/back-of-the-envelope
Public URL: https://backoftheenvelope.app/

**Comment by chanmathew** [comment] 2024-04-13 15:36
I'm having the same issue on 3.0.22, Sveltekit. `onFinish` is not firing at all.

**Comment by hu-qi** [comment] 2024-04-15 03:35
> I'm having the same issue on 3.0.22, Sveltekit. `onFinish` and `onResponse` is not firing at all.
> 
> Downgraded to 3.0.19 and that seems to work.

In my case, the same issue on `3.0.22`, and `3.0.19` is work.    
Ask for help: are there any incompatible changes?

**Comment by lgrammel** [comment] 2024-04-15 07:12
This is potentially a duplicate of https://github.com/vercel/ai/issues/1316

You can check out https://github.com/vercel/ai/issues/1316#issuecomment-2048346351 for upgrade instructions.

**Comment by myudak** [comment] 2024-06-05 09:56
me too the onFinish in nextjs 14 doesnt work

**Closed** 2024-07-08 20:53 UTC

**Comment by lgrammel** [comment] 2026-07-22 17:57
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes callback behavior that worked in an earlier version but fails in a current release, making it a concrete regression in existing SDK behavior.

### Evidence
- The reporter states that `useChat` streams successfully but never invokes its configured `onFinish` callback.
- Other users reproduce the failure in AI SDK 3.0.22 across SvelteKit and Next.js 14; one also reports that `onResponse` does not fire.
- A commenter reports that downgrading from 3.0.22 to 3.0.19 restores the callbacks, indicating a regression.
- A maintainer identifies a potentially duplicate issue and links upgrade instructions, but does not reframe this as a feature request.
