### ISSUE TITLE
streamObject breaks with undefined (Mistral provider)

### ISSUE THREAD

**Issue by mishushakov** [vercel/ai#2785] opened 2024-08-23 12:33 UTC
### Description

Mistral provider breaks partial object stream by returning undefined when using `streamObject`.

Video:

https://github.com/user-attachments/assets/497c4980-3b9a-4f45-bf6b-3f363fe4a34d

### Code example

My schema:

```ts
export const artifactSchema = z.object({
  commentary: z.string().describe(`Describe what you're about to do and the steps you want to take for generating the artifact in great detail.`),
  template: z.string().describe('Name of the template used to generate the artifact.'),
  title: z.string().describe('Short title of the artifact. Max 5 characters.'),
  description: z.string().describe('Short description of the artifact. Max 10 characters.'),
  additional_dependencies: z.array(z.string()).describe('Additional dependencies required by the artifact. Do not include dependencies that are already included in the template.'),
  has_additional_dependencies: z.boolean().describe('Detect if additional dependencies that are not included in the template are required by the artifact.'),
  install_dependencies_command: z.string().describe('Command to install additional dependencies required by the artifact.'),
  port: z.number().nullable().describe('Port number used by the resulted artifact. Null when no ports are exposed.'),
  code: z.string().describe('Code generated by the artifact.'),
  file_path: z.string().describe('Relative path to the file, including the file name.'),
})

export type ArtifactSchema = z.infer<typeof artifactSchema>
```

```ts
  const stream = await streamObject({
    model: modelClient as LanguageModel,
    schema,
    system: `You are a skilled software engineer. You do not make mistakes. Generate an artifact. You can install additional dependencies. You can use one of the following templates:\n${templatesToPrompt(template)}`,
    prompt,
  })
```

### Additional context

version:

```json
"@ai-sdk/mistral": "^0.0.37"
```

**Comment by mishushakov** [comment] 2024-08-23 12:37
Happens primarily with Mistral large

**Comment by lgrammel** [comment] 2024-08-30 11:44
Tried reproducing it with the code below, but failed so far:

```ts
import { mistral } from '@ai-sdk/mistral';
import { streamObject } from 'ai';
import dotenv from 'dotenv';
import { z } from 'zod';

dotenv.config();

const artifactSchema = z.object({
  commentary: z
    .string()
    .describe(
      `Describe what you're about to do and the steps you want to take for generating the artifact in great detail.`,
    ),
  template: z
    .string()
    .describe('Name of the template used to generate the artifact.'),
  title: z.string().describe('Short title of the artifact. Max 5 characters.'),
  description: z
    .string()
    .describe('Short description of the artifact. Max 10 characters.'),
  additional_dependencies: z
    .array(z.string())
    .describe(
      'Additional dependencies required by the artifact. Do not include dependencies that are already included in the template.',
    ),
  has_additional_dependencies: z
    .boolean()
    .describe(
      'Detect if additional dependencies that are not included in the template are required by the artifact.',
    ),
  install_dependencies_command: z
    .string()
    .describe(
      'Command to install additional dependencies required by the artifact.',
    ),
  port: z
    .number()
    .nullable()
    .describe(
      'Port number used by the resulted artifact. Null when no ports are exposed.',
    ),
  code: z.string().describe('Code generated by the artifact.'),
  file_path: z
    .string()
    .describe('Relative path to the file, including the file name.'),
});

async function main() {
  const result = await streamObject({
    model: mistral('mistral-large-latest'),
    schema: artifactSchema,
    system: `You are a skilled software engineer. You do not make mistakes. Generate an artifact. You can install additional dependencies.`,
    prompt: `Write a simple web server in Kotlin that listens on port 8080 and returns "Hello, World!" when the user visits the root URL.`,
  });

  let counter = 0;

  for await (const partialObject of result.partialObjectStream) {
    if (partialObject === undefined) {
      counter++;
      continue;
    }
    console.clear();
    console.log(partialObject);
  }

  console.log(`Counter: ${counter}`);
}

main().catch(console.error);
```

@mishushakov do you have an example that always reproduces?

**Comment by mishushakov** [comment] 2024-08-30 12:26
try a more vague prompt, I find it works almost always with a good prompt.

eg. "a todo app"

**Comment by lgrammel** [comment] 2024-08-30 12:32
Still was not able to repro, tried "a todo app" and "a note taking app"

**Comment by lgrammel** [comment] 2024-09-19 15:57
Closing since I cannot reproduce it.

**Closed by lgrammel** 2024-09-19 15:57 UTC
Labels: bug, reproduction needed, ai/provider

**Comment by lgrammel** [comment] 2026-07-22 17:06
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This describes a concrete failure in existing streaming behavior—unexpected `undefined` partial objects—rather than requesting new functionality. Reproduction was unsuccessful, so confidence is limited.

### Evidence
- Reporter states that `streamObject` with the Mistral provider emits `undefined` in `partialObjectStream`, primarily with Mistral Large.
- The report includes the schema, invocation code, and provider version (`@ai-sdk/mistral` 0.0.37).
- A maintainer attempted reproduction with similar prompts but could not reproduce and closed the issue.
