### ISSUE TITLE
generateObject fails with any Perplexity api models

### ISSUE THREAD

**Issue by clacladev** [vercel/ai#2794] opened 2024-08-25 20:21 UTC
### Description

I have an app which uses Vercel AI SDK to create an article summary and to generate structured data (json).

I am successful with Groq Llama-3.1-70B, but I fail using any model from Perplexity (e.g. `llama-3.1-sonar-large-128k-online`). I always get the error `NoObjectGeneratedError [AI_NoObjectGeneratedError]: No object generated`.

The [AI sdk docs](https://sdk.vercel.ai/providers/ai-sdk-providers/perplexity#example) explicitly mention that `generateObject` should work.

What is wrong?

### Code example
```ts
"use server";

import { generateObject } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import { z } from "zod";

const provider = createOpenAI({
  apiKey: process.env.PERPLEXITY_API_KEY,
  baseURL: "https://api.perplexity.ai/",
});
const model = provider("llama-3.1-sonar-large-128k-online");

// Works with Groq
// const provider = createOpenAI({
//   apiKey: process.env.GROQ_API_KEY,
//   baseURL: "https://api.groq.com/openai/v1",
// });
// const model = provider("llama-3.1-70b-versatile");

const articleSummarySchema = z.object({
  title: z.string(),
  summary: z.string(),
});

export type ArticleSummary = z.infer<typeof articleSummarySchema>;

export async function getLearningPoints(
  inputUrl: string
): Promise<ArticleSummary> {
  if (!inputUrl) throw new Error("No URL provided");

  const result = await generateObject({
    model,
    schema: articleSummarySchema,
    system: `Return only a plain JSON object without including it in a code block with markdown formatting.
  Just a plain JSON object. Do not include any markdown formatting in your response.
  Please return only a JSON with the following format: 
{
  "title": "Article title",
  "summary": "Article shortsummary",
}`,
    prompt: `Make a a summary of this article: ${inputUrl}`,
  });

  return result.object;
}

```

### Additional context

I tried to follow the [solution to this issue](https://github.com/vercel/ai/issues/2378) without success. It seems that AI sdk has changed.

**Comment by lgrammel** [comment] 2024-08-26 07:05
The docs are incorrect. Perplexity does not support object generation.

Duplicate of #2378

**Comment by lgrammel** [comment] 2024-08-26 07:09
https://github.com/vercel/ai/pull/2797

**Closed** 2024-08-26 14:31 UTC
Labels: bug, docs

**Comment by clacladev** [comment] 2024-08-27 09:12
@lgrammel thanks for the clarification

**Comment by lgrammel** [comment] 2026-07-22 17:05
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The reported failure results from incorrect provider documentation rather than broken supported SDK behavior, so this is a documentation issue.

### Evidence
- The documentation stated that Perplexity supports `generateObject`, but calls produced `NoObjectGeneratedError`.
- A maintainer clarified that Perplexity does not support object generation and that the documentation was incorrect.
- The maintainer linked PR #2797 to address the issue and marked it as a duplicate of #2378.
