### ISSUE TITLE
Nuxt: Updating AI SDK from 3.0.19 to later causes error in useChat

### ISSUE THREAD

**Issue by dosstx** [vercel/ai#1344] opened 2024-04-14 11:26 UTC
### Description

Nuxt app works fine with ai@3.0.19 . However, updating to latest AI SDK causes the following browser error (shown via the `onError` callback in `useChat`):

### Error
`Failed to parse stream string. Invalid code`

Reverting to ai@3.0.19 is the last version that works before the above error begins to show starting at version 3.0.20.

### Code example

```
const {
	messages,
	input,
	handleSubmit,
	setMessages,
	reload,
	isLoading,
	stop,
	append
} = useChat({
	api: config.public.chatUrl,
	headers: { "Content-Type": "application/json" },
	body: agent,
	onError: (error) => {
		isLoading.value = false
		console.log("onError from useChat: ", error)
		errorMessage.value = error
	}
})
```

### Additional context

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      routeRules, devtools, nitro, modules, eslint, runtimeConfig, vuefire, image        
- Runtime Modules:  @nuxt/ui@2.15.2, @nuxt/image@1.5.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-vuefire@1.0.2, @vueuse/nuxt@10.9.0, @nuxt/eslint@0.3.6, @nuxt/content@2.12.1, @nuxt/fonts@0.6.1
- Build Modules:    -
------------------------------

**Comment by dosstx** [comment] 2024-04-14 11:30
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      routeRules, devtools, nitro, modules, eslint, runtimeConfig, vuefire, image        
- Runtime Modules:  @nuxt/ui@2.15.2, @nuxt/image@1.5.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-vuefire@1.0.2, @vueuse/nuxt@10.9.0, @nuxt/eslint@0.3.6, @nuxt/content@2.12.1, @nuxt/fonts@0.6.1
- Build Modules:    -
------------------------------

**Comment by lgrammel** [comment] 2024-04-14 11:43
Duplicate of #1316

See https://github.com/vercel/ai/issues/1316#issuecomment-2048346351 for upgrade instructions.

**Closed by lgrammel** 2024-04-14 11:43 UTC

**Comment by lgrammel** [comment] 2026-07-22 17:54
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
Although the report describes a concrete upgrade failure, the maintainer treated it as duplicate bookkeeping and directed the user to migration instructions rather than tracking a separate SDK defect.

### Evidence
- Maintainer explicitly marked the issue as a duplicate of #1316.
- The maintainer redirected the reporter to upgrade instructions in the duplicate issue.
- The reported error occurs when upgrading from 3.0.19 to 3.0.20 or later.
