### ISSUE TITLE
bug: react data stream json decoding

### ISSUE THREAD

**Issue by todowa** [vercel/ai#519] opened 2023-08-26 13:13 UTC
Data streaming of JSON doesn't work correctly when using experimental streaming within React `use-chat`.

This is because the shared helper function `getStreamStringTypeAndValue` (line 85 in `ai/packages/core/shared/utils.ts`) decodes the JSON, and then `getStreamedResponse` (line 217 in `ai/packages/core/react/use-chat.ts`) tries to do it again.

**Comment by MaxLeiter** [comment] 2023-08-26 19:09
Can you provide an example showing the problem? 

How are you appending data? the below solution from the example works
```

export async function POST(req: Request) {
  const { messages } = await req.json()

  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo-0613',
    stream: true,
    messages,
    functions
  })

  const data = new experimental_StreamData()
  const stream = OpenAIStream(response, {
    experimental_onFunctionCall: async (
      { name, arguments: args },
      createFunctionCallMessages
    ) => {
      if (name === 'get_current_weather') {
        // Call a weather API here
        const weatherData = {
          temperature: 20,
          unit: args.format === 'celsius' ? 'C' : 'F'
        }

        data.append({
          text: 'Some custom data'
        })

        const newMessages = createFunctionCallMessages(weatherData)
        return openai.chat.completions.create({
          messages: [...messages, ...newMessages],
          stream: true,
          model: 'gpt-3.5-turbo-0613'
        })
      }
    },
    onCompletion(completion) {
      console.log('completion', completion)
    },
    onFinal(completion) {
      data.close()
    },
    experimental_streamData: true
  })

  data.append({
    text: 'Hello, how are you?'
  })

  return new StreamingTextResponse(stream, {}, data)
}
```

**Comment by MaxLeiter** [comment] 2023-09-01 13:39
Closing without a reproduction or more information. @todowa @ewianda please let us know if you are still encountering issues.

**Closed by MaxLeiter** 2023-09-01 13:39 UTC

**Comment by lgrammel** [comment] 2026-07-22 18:50
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This is framed as a concrete failure in existing streaming behavior, so it is a bug report, although the lack of reproduction and the maintainer's working example reduce confidence.

### Evidence
- The report states that JSON data streaming with experimental React `use-chat` fails because the payload is decoded twice.
- It identifies the two specific helpers allegedly performing duplicate decoding.
- A maintainer provided a working example and closed the issue because no reproduction or further information was supplied.
