### ISSUE TITLE
Supporting Deepgram AI Integrations

### ISSUE THREAD

**Issue by metecan** [vercel/ai#1100] opened 2024-03-05 08:01 UTC
### Feature Description

I need to integrate speech-to-text into my own projects along with other AI models and I look forward to Deepgram, an affordable solution, being supported by Vercel AI for seamless integration. This collaboration holds the promise of achieving a more effective and affordable voice-to-text solution for my projects.

[Deepgram](https://deepgram.com/) & [Deepgram Docs](https://developers.deepgram.com/docs/introduction)

**Comment by MaxLeiter** [comment] 2024-07-08 22:32
Thanks for the issue. I'm going to close this in favor of tracking in https://github.com/vercel/ai/issues/885.

Specific providers will be able to provide their own AI SDK providers, similar to what they do today for chat: https://sdk.vercel.ai/providers/ai-sdk-providers

**Closed by MaxLeiter** 2024-07-08 22:32 UTC

**Comment by lgrammel** [comment] 2026-07-22 18:03
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the original request is for a new integration, the maintainer identifies this issue as duplicate bookkeeping in favor of an existing tracking issue.

### Evidence
- The request asks for new Deepgram speech-to-text provider support.
- A maintainer closed the issue as a duplicate of #885, where provider integration is being tracked.
