### ISSUE TITLE
Invalid JSON payload received (Google Provider).

### ISSUE THREAD

**Issue by mishushakov** [vercel/ai#2743] opened 2024-08-20 16:13 UTC
### Description

When using `streamObject`, I'm getting the following error with the Google AI provider:

```js
{
    code: 400,
    message: `Invalid JSON payload received. Unknown name "type" at 'generation_config.response_schema.properties[7].value': Proto field is not repeating, cannot start list.`,
    status: 'INVALID_ARGUMENT'
}
```

### Additional context

using:

```
"@ai-sdk/google": "^0.0.41"
```

**Comment by mishushakov** [comment] 2024-08-20 16:23
Might be related? #2564

**Comment by lgrammel** [comment] 2024-08-21 08:59
The basic stream object example works for Google: https://github.com/vercel/ai/blob/main/examples/ai-core/src/stream-object/google.ts

I suspect it has something to do with the specifics of the schema. Can you share the schema that you are using, or try to narrow it down to the part of the schema that causes the failure?

**Comment by sullyo** [comment] 2024-08-21 15:31
Running into this issue as well. 

It involves deeply nested zod schemas, which do work on anthropic and openai but on on gemini (broken on both vertex and google studio)


Specifically it breaks when you have a union with zod:

```
const personSchema = z.object({
  name: z.string(),
  age: z.number(),
  contact: z.union([
    z.object({
      type: z.literal("email"),
      value: z.string(),
    }),
    z.object({
      type: z.literal("phone"),
      value: z.string(),
    }),
  ]),
  occupation: z.union([
    z.object({
      type: z.literal("employed"),
      company: z.string(),
      position: z.string(),
    }),
    z.object({
      type: z.literal("student"),
      school: z.string(),
      grade: z.number(),
    }),
    z.object({
      type: z.literal("unemployed"),
    }),
  ]),
});
```

**Comment by lgrammel** [comment] 2024-08-21 16:13
I logged the JSON schema for the above person schema:

```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    },
    "contact": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "const": "email"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "value"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "const": "phone"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "value"
          ]
        }
      ]
    },
    "occupation": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "const": "employed"
            },
            "company": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "company",
            "position"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "const": "student"
            },
            "school": {
              "type": "string"
            },
            "grade": {
              "type": "number"
            }
          },
          "required": [
            "type",
            "school",
            "grade"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "const": "unemployed"
            }
          },
          "required": [
            "type"
          ]
        }
      ]
    }
  },
  "required": [
    "name",
    "age",
    "contact",
    "occupation"
  ]
}
```

Here are the errors that I'm getting:
```
  data: {
    error: {
      code: 400,
      message: `Invalid JSON payload received. Unknown name "const" at 'generation_config.response_schema.properties[2].value.any_of[0].properties[0].value': Cannot find field.\n` +
        `Invalid JSON payload received. Unknown name "const" at 'generation_config.response_schema.properties[2].value.any_of[1].properties[0].value': Cannot find field.\n` +
        `Invalid JSON payload received. Unknown name "const" at 'generation_config.response_schema.properties[3].value.any_of[0].properties[0].value': Cannot find field.\n` +
        `Invalid JSON payload received. Unknown name "const" at 'generation_config.response_schema.properties[3].value.any_of[1].properties[0].value': Cannot find field.\n` +
        `Invalid JSON payload received. Unknown name "const" at 'generation_config.response_schema.properties[3].value.any_of[2].properties[0].value': Cannot find field.`,
      status: 'INVALID_ARGUMENT'
    }
  },
  ```
  
  I'm not sure if Google supports JSON schema 7.

**Comment by lgrammel** [comment] 2024-08-21 16:23
Caused by differences between JSON Schema 7 (used by AI SDK) and OpenAPI Schema (used by Google GenAI & Vertex)

**Comment by lgrammel** [comment] 2024-08-21 17:25
With a full conversion to OpenAPI schema, I'm running into issues with the Google provider: https://github.com/vercel/ai/pull/2760

Need to investigate if they support anyOf etc

**Comment by lgrammel** [comment] 2024-08-21 17:28
Unless I'm missing something, Google does not support `anyOf` etc:

From Vertex:
```
/**
 * Contains the list of OpenAPI data types
 * as defined by https://swagger.io/docs/specification/data-models/data-types/
 */
export declare enum FunctionDeclarationSchemaType {
    /** String type. */
    STRING = "STRING",
    /** Number type. */
    NUMBER = "NUMBER",
    /** Integer type. */
    INTEGER = "INTEGER",
    /** Boolean type. */
    BOOLEAN = "BOOLEAN",
    /** Array type. */
    ARRAY = "ARRAY",
    /** Object type. */
    OBJECT = "OBJECT"
}
/**
 * Schema for parameters passed to {@link FunctionDeclaration.parameters}.
 */
export interface FunctionDeclarationSchema {
    /** The type of the parameter. */
    type: FunctionDeclarationSchemaType;
    /** The format of the parameter. */
    properties: {
        [k: string]: FunctionDeclarationSchemaProperty;
    };
    /** Optional. Description of the parameter. */
    description?: string;
    /** Optional. Array of required parameters. */
    required?: string[];
}
/**
 * Schema is used to define the format of input/output data.
 * Represents a select subset of an OpenAPI 3.0 schema object.
 * More fields may be added in the future as needed.
 */
export interface FunctionDeclarationSchemaProperty {
    /**
     * Optional. The type of the property. {@link
     * FunctionDeclarationSchemaType}.
     */
    type?: FunctionDeclarationSchemaType;
    /** Optional. The format of the property. */
    format?: string;
    /** Optional. The description of the property. */
    description?: string;
    /** Optional. Whether the property is nullable. */
    nullable?: boolean;
    /** Optional. The items of the property. {@link FunctionDeclarationSchema} */
    items?: FunctionDeclarationSchema;
    /** Optional. The enum of the property. */
    enum?: string[];
    /** Optional. Map of {@link FunctionDeclarationSchema}. */
    properties?: {
        [k: string]: FunctionDeclarationSchema;
    };
    /** Optional. Array of required property. */
    required?: string[];
    /** Optional. The example of the property. */
    example?: unknown;
}
```

**Comment by lgrammel** [comment] 2024-08-21 17:44
I'll need to introduce a flag on the Gemini provider that distinguishes grammar-guided generation from loose generation.

**Comment by sullyo** [comment] 2024-08-21 18:52
What would be a good interm solution - or is it better to wait?

**Comment by mishushakov** [comment] 2024-08-21 19:36
Here's my schema, if it helps:

```ts
export const artifactSchema = z.object({
  commentary: z.string().describe('Describe what you just did and the process of generating the artifact.'),
  template: z.string().describe('Name of the template used to generate the artifact.'),
  title: z.string().describe('Short title of the artifact. Max 5 characters.'),
  description: z.string().describe('Short description of the artifact. Max 10 characters.'),
  additional_dependencies: z.array(z.string()).describe('Additional dependencies required by the artifact. Do not include dependencies that are already included in the template.'),
  has_additional_dependencies: z.boolean().describe('Detect if additional dependencies that are not included in the template are required by the artifact.'),
  install_dependencies_command: z.string().describe('Command to install additional dependencies required by the artifact.'),
  port: z.number().nullable().describe('Port number used by the resulted artifact. Null when no ports are exposed.'),
  code: z.string().describe('Code generated by the artifact.'),
  file_path: z.string().describe('Relative path to the file, including the file name.'),
})
```

it's pretty flat as you see

**Comment by mishushakov** [comment] 2024-08-21 19:58
The field that is causing the error:

```ts
port: z.number().nullable().describe('Port number used by the resulted artifact. Null when no ports are exposed.'),
```

When it is non-nullable then it is working. Any tips?

**Comment by lgrammel** [comment] 2024-08-22 11:05
Addressed in the latest version of the google provider, see also https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai#troubleshooting-schema-limitations

**Closed by lgrammel** 2024-08-22 11:05 UTC
Labels: bug, ai/provider

**Comment by mishushakov** [comment] 2024-08-22 11:26
Works for me 🥳

**Comment by lgrammel** [comment] 2026-07-22 17:08
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This was a concrete provider failure when processing a supported Zod schema, subsequently fixed in the Google provider.

### Evidence
- `streamObject` with the Google provider returned a 400 `INVALID_ARGUMENT` for a schema containing `z.number().nullable()`.
- The same schema worked when the field was made non-nullable, isolating the failure to schema conversion/compatibility.
- A maintainer stated that the issue was addressed in the latest Google provider version, and the reporter confirmed the fix worked.
