### ISSUE TITLE
AI SDK not work with SGLang

### ISSUE THREAD

**Issue by wizd** [vercel/ai#2548] opened 2024-08-05 10:09 UTC
### Description

with the latest ai sdk ver 3.3.0, it works well with vllm, but not with SGLang. I have a lot of error message like bellow.

```
[AI_TypeValidationError]: Type validation failed: Value: {"id":"6907ddbebf1b4e95b814ccd34633f107","object":"chat.completion.chunk","created":1722852140,"model":"gpt-4","choices":[{"index":0,"delta":{"role":null,"content":"转"},"logprobs":null,"finish_reason":"None"}]}.
Error message: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "expected": "'assistant'",
            "received": "null",
            "code": "invalid_type",
            "path": [
              "choices",
              0,
              "delta",
              "role"
            ],
            "message": "Expected 'assistant', received null"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "error"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]
    at value (/app/ai-chatbot/.next/server/chunks/54.js:11:7568)
    at p (/app/ai-chatbot/.next/server/chunks/54.js:11:7749)
    ... 4 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: d [ZodError]: [
    {
      "code": "invalid_union",
      "unionErrors": [
        {
          "issues": [
            {
              "expected": "'assistant'",
              "received": "null",
              "code": "invalid_type",
              "path": [
                "choices",
                0,
                "delta",
                "role"
              ],
              "message": "Expected 'assistant', received null"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "code": "invalid_type",
              "expected": "object",
              "received": "undefined",
              "path": [
                "error"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        }
      ],
      "path": [],
      "message": "Invalid input"
    }
  ]
      at get error [as error] (/app/ai-chatbot/.next/server/chunks/2874.js:1:9187)
      at value (/app/ai-chatbot/.next/server/chunks/54.js:11:7611)
      at p (/app/ai-chatbot/.next/server/chunks/54.js:11:7749)
      at Object.transform (/app/ai-chatbot/.next/server/chunks/54.js:11:10739)
      at ensureIsPromise (node:internal/webstreams/util:192:19)
      at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:505:18)
      at node:internal/webstreams/transformstream:550:16
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    issues: [ [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object] ]
  },
  value: {
    id: '6907ddbebf1b4e95b814ccd34633f107',
    object: 'chat.completion.chunk',
    created: 1722852140,
    model: 'gpt-4',
    choices: [ [Object] ]
  }
}
```

### Code example

file genAnywhere_server.ts
```
'use server';

import { streamText } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { createStreamableValue } from 'ai/rsc';

export async function generate(input: string, system?: string) {
  const stream = createStreamableValue('')

  ;(async () => {
    const openai = createOpenAI({
      baseURL: process.env.NEXT_PUBLIC_DEFAULT_MODEL_API_BASEURL,
      apiKey: process.env.NEXT_PUBLIC_DEFAULT_MODEL_API_KEY
    })

    const { textStream } = await streamText({
      model: openai(process.env.NEXT_PUBLIC_DEFAULT_MODEL_NAME!),
      system: system,
      prompt: input
    })

    for await (const delta of textStream) {
      stream.update(delta)
    }

    stream.done()
  })()

  return { output: stream.value }
}
```

file genAnywhere.tsx
```
'use client';

import { useState, useEffect } from 'react';
import { generate } from './genAnywhere_server';
import { readStreamableValue } from 'ai/rsc';

export const maxDuration = 30;

export default function GenAnywhere({ text }: { text: string }) {
  const [generation, setGeneration] = useState<string>('');
  const [debugInfo, setDebugInfo] = useState<string>('');

  useEffect(() => {
    const generateText = async () => {
      setDebugInfo(`输入文本: ${text}`);
      const { output } = await generate(text);
      let fullGeneration = '';
      for await (const delta of readStreamableValue(output)) {
        fullGeneration += delta;
        setGeneration(fullGeneration);
      }
      setDebugInfo(prevInfo => `${prevInfo}\n最终翻译: ${fullGeneration}`);
    };

    generateText();
  }, [text]);

  return (
    <div>
      <div>{generation}</div>
      <pre>{debugInfo}</pre>
    </div>
  );
}
```

### Additional context

Run sglang local openai api server:

```
docker run -d --gpus all \
    -p 5010:5010 \
    --name sglang \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    -v ~/data/models:/models \
    --env "HF_TOKEN=hf_...j" \
    --ipc=host \
    lmsysorg/sglang:latest \
    python3 -m sglang.launch_server --model-path /models/Llama3.1-8B-Chinese-Chat --host 0.0.0.0 --port 5010 --quantization fp8 --context-length 64000
    
```

SGLang project repo:
https://github.com/sgl-project/sglang

**Comment by lgrammel** [comment] 2024-08-06 08:43
fix landed in main

**Closed by lgrammel** 2024-08-06 08:43 UTC
Labels: ai/provider

**Comment by lgrammel** [comment] 2026-07-22 17:14
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete runtime compatibility failure in existing SDK behavior, and the maintainer confirmed it required and received a fix.

### Evidence
- AI SDK 3.3.0 rejects SGLang streaming responses because `choices[0].delta.role` is `null`, producing a Zod validation error.
- The same integration reportedly works with vLLM, indicating a concrete compatibility failure with SGLang's OpenAI-compatible API.
- A maintainer linked PR #2557 and confirmed that a fix landed in main.
