### ISSUE TITLE
Error when not using Bedrock's `sessionToken` in AI SDK

### ISSUE THREAD

**Issue by agamm** [vercel/ai#3725] opened 2024-11-17 01:32 UTC
### Description

If you try to use bedrock without the `sessionToken` parameter it will error, assuming you don't have an env vars/aws credentials file used as a default.

### Code example

```
return createAmazonBedrock({
  region: "us-east-1",
  accessKeyId: "<accessID>",
  secretAccessKey: "<token>",
})("anthropic.claude-3-5-sonnet-20241022-v2:0");
```

### Additional context

To solve add:
```
sessionToken: ""
```

**Comment by shaper** [comment] 2024-11-18 18:44
Thanks for raising! Perhaps this is #3018 -- #3130 captures discussion, intent is to clarify in docs that cloud function environments can have a session token defined that's silently used without dev awareness (just a guess as to what you are experiencing).

Workarounds for now include what you did, or using `bedrockOptions` as in the linked issue. We plan to update the docs soon to help prevent others from falling into this trap, and figure out any API changes separately.

**Comment by shaper** [comment] 2024-11-20 19:13
Marking as duplicate of #3018, we've updated the docs as well.

**Closed by shaper** 2024-11-20 19:13 UTC
Labels: bug, ai/provider

**Comment by lgrammel** [comment] 2026-07-22 16:38
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the original report describes a concrete failure, the maintainer resolved this issue as duplicate bookkeeping for #3018 rather than as an independently tracked bug or documentation change.

### Evidence
- The reporter describes an error when Bedrock credentials omit `sessionToken`, with an empty token as a workaround.
- A maintainer linked the behavior to #3018, explained the environment-token interaction, and provided existing workarounds.
- The maintainer ultimately marked this issue as a duplicate of #3018 and noted that the documentation had been updated.
