### ISSUE TITLE
Handle error/abort for `createStreamableUI`, `createStreamableValue` in `ai/rsc`

### ISSUE THREAD

**Issue by phuctm97** [vercel/ai#1167] opened 2024-03-16 07:54 UTC
### Feature Description

Something like:

```ts
import { createStreamableUI, createStreamableValue } from "ai/rsc";

const ui = createStreamableUI();
const value = createStreamableValue();

ui.on("error", () => {});
value.on("close", () => {});
```

Besides, it would be nice to be able to "natively" communicate error to the React (UI) by calling `done` with an error:

```ts
// This will throw an error in the React tree up to the closest error boundary from the streamable UI (or components consuming the streamable value)
ui.done(new Error("Something went wrong.");
```

### Use Case

The client may have trouble or abort connection with a streamable UI or value. Currently, in these scenarios, there is no way to abort running async tasks in corresponding server actions.

**Comment by yahorbarkouski** [comment] 2024-03-30 14:26
any idea how to handle 500 codes from OpenAI with current setup?

**Comment by lgrammel** [comment] 2024-08-14 06:52
Duplicate of #1122

**Closed by lgrammel** 2024-08-14 06:52 UTC
Labels: duplicate

**Comment by lgrammel** [comment] 2026-07-22 18:00
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for new error propagation and cancellation capabilities rather than reporting a failure of existing documented behavior. The duplicate status does not change the substantive request type.

### Evidence
- Requests new error/close event handlers for `createStreamableUI` and `createStreamableValue`.
- Proposes allowing `done(Error)` to propagate errors to a React error boundary.
- States there is currently no way to abort corresponding server-side async tasks when clients disconnect or abort.
- A maintainer notes the request is a duplicate of #1122.
